name: Check

on: push

jobs:
  type:
    name: Type
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.6.1"

      - name: Install mypy
        run: pip install mypy

      - name: Install dependencies
        run: poetry install

      # - name: Setup Types
      #   run: mypy --install-types --non-interactive

      - name: Check Types
        run: make test

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.6.1"

      - name: Install dependencies
        run: poetry install

      - name: Setup Unit Tests
        run: cp ./env.sample.jsonc ./env.jsonc

      - name: Run Unit Tests
        run: make test
